### ISSUE TITLE
E-mail login requires an adapter

### ISSUE THREAD

**Issue by JanKups** [OpenSaasAU/keystone-nextjs-auth#107]
It is possible to add an adapter to Keystone-next-auth? The [email](https://next-auth.js.org/providers/email) provider requires an [adapter](https://next-auth.js.org/adapters/overview) for the database. 

```
[next-auth][error][EMAIL_REQUIRES_ADAPTER_ERROR] 
https://next-auth.js.org/errors#email_requires_adapter_error E-mail login requires an adapter. MissingAdapter [MissingAdapterError]: E-mail login requires an adapter.
```

Documentation provides the following for Prisma:
```
import { PrismaAdapter } from "@next-auth/prisma-adapter"
import { PrismaClient } from "@prisma/client"
```
```
export default NextAuth({
  adapter: PrismaAdapter(prisma),
  providers: [
  ...
  ],
})

```

**Comment by borisno2** [comment]
Hey @JanKups 
Thanks for reaching out, unfortunately there is not currently a way to setup an adapter. I have been thinking it would be nice to have, and try to get it working with the keystone prisma configuration, having gotten much further than a thought though...
Thanks,
Josh

**Comment by JanKups** [comment]
@borisno2 Thanks Josh for the quick reply!

I'll just opt for [Auth0](https://next-auth.js.org/providers/auth0), they also provide an easy way to authenticate via email.
