### ISSUE TITLE
Can we add `autoUpdate` option?

### ISSUE THREAD

**Issue by IMalaniak** [OpenSaasAU/keystone-nextjs-auth#117]
[NextAuthPage.tsx](https://github.com/OpenSaasAU/keystone-nextjs-auth/blob/main/packages/keystone-nextjs-auth/src/pages/NextAuthPage.tsx)

In this file line 96 I see a piece of code that is commented out. As I've understood this is planned for `autoUpdate` option ;) 
That would be really great to have this option, I can also contribute if needed.

**Comment by borisno2** [comment]
Hey @IMalaniak, Sorry for the slow reply... Yes I had planned to put an update there... Happy for a PR if you want to have a got at it. Let me know if you need any assistance.

**Comment by borisno2** [comment]
Resolved in latest release

**Comment by IMalaniak** [comment]
@borisno2 thanx a lot! Sorry, that I could not find some time to start some PR on that ;)

**Comment by borisno2** [comment]
All good @IMalaniak
