### ISSUE TITLE
How do I access `role` within session data?

### ISSUE THREAD

**Issue by wendtcode** [OpenSaasAU/keystone-nextjs-auth#135]
I see in the [access.ts](https://github.com/OpenSaasAU/keystone-nextjs-auth/blob/main/backend/access.ts#L13) file, the session appears to have a `role` property as part of it's data. I don't have that data available within my session.

![Screen Shot 2022-02-28 at 6 21 25 AM](https://user-images.githubusercontent.com/48448749/155982851-ecda5855-2337-4838-b663-6116f8e7ed49.png)

**Comment by borisno2** [comment]
Hey @wendtcode the session data is set in your `keystone.ts` file.
To add role you would do something like
```javascript
const auth = createAuth({
  listKey: 'User',
  identityField: 'subjectId',
  sessionData: `id name email role { id name }`,
  autoCreate: true, 
```
That is if role is a separate list, this is graphql so you can add anything that sits on the `role` list
Hope this helps.

**Comment by wendtcode** [comment]
Aha! Thanks for the suggestions!
