### ISSUE TITLE
npm shows 4 high severity vulnerabilities

### ISSUE THREAD

**Issue by muhad-bk** [OpenSaasAU/keystone-nextjs-auth#165]
# npm audit report

async  <2.6.4
Severity: high
Prototype Pollution in async - https://github.com/advisories/GHSA-fwr7-v2mv-hh25
No fix available
node_modules/jake/node_modules/async
  jake  >=8.0.1
  Depends on vulnerable versions of async
  node_modules/jake
    ejs  >=3.1.2
    Depends on vulnerable versions of jake
    node_modules/ejs
      @opensaas/keystone-nextjs-auth  *
      Depends on vulnerable versions of ejs
      node_modules/@opensaas/keystone-nextjs-auth

4 high severity vulnerabilities

**Comment by borisno2** [comment]
Hi @muhad-bk 
Thanks for flagging this, these packages have now been patched.
Thanks
