### ISSUE TITLE
Can I get a users session information?

### ISSUE THREAD

**Issue by limegorilla** [OpenSaasAU/keystone-nextjs-auth#233]
So I'm using this in my Keystone app and my end goal is to replace the default dashboard with a much more complete dashboard with overviews across many sources.

I need to be able to get the currently signed in user to be able to show relevant and scoped information - such as bits they can access depending on their role.

**Comment by borisno2** [comment]
Hi and thanks for reaching out. 
There are a couple of different ways to get a user's session information
You can use the `next-auth/react` `useSession` or by the `authenticatedItem` graphql query. Both of these can be found in the frontend example https://github.com/OpenSaasAU/keystone-nextjs-auth/blob/main/apps/ks-frontend-demo/pages/index.tsx
