### ISSUE TITLE
Keystone Removed generateNodeAPI Experimental Feature

### ISSUE THREAD

**Issue by StephenStrickland** [OpenSaasAU/keystone-nextjs-auth#241]
Hey Team,

A few days ago the Keystone team removed the experimental feature `generateNodeAPI`. 

Since this package requires `generateNodeAPI`, what's the best next steps to supporting this breaking change?

PR removing the feature: https://github.com/keystonejs/keystone/pull/7957

Definitely open to assist in any way I can.

**Comment by borisno2** [comment]
Hey @StephenStrickland thanks for reaching out, and good to know people are keeping an eye on this...

`generateNodeAPI` is actually getting replaced with a much better alternative - `getContext` - this package can switch to that once it has been released - keystonejs/keystone#7954 it should be a fairly straightforward change.

**Comment by limegorilla** [comment]
Is there any update on this? This has now been fully removed as far as I can tell so this package is now not working.

**Comment by borisno2** [comment]
Hey @limegorilla the package has been updated so that is works with the latest keystone version. If you upgrade this package to the latest it should work. Let us know if you have any issues...

**Comment by limegorilla** [comment]
Ahhh - apologies!

All working!
