### ISSUE TITLE
Errors when building front end app

### ISSUE THREAD

**Issue by smarques** [OpenSaasAU/keystone-nextjs-auth#254]
Hi, I tried to build the example front end app using its docker file, but I got the following errors:

1) linting error
`> [6/6] RUN yarn build:                                                                                            
#10 0.649 yarn run v1.22.19                                                                                         
#10 0.707 $ next build
#10 1.517 Attention: Next.js now collects completely anonymous telemetry regarding usage.
#10 1.518 This information is used to shape Next.js' roadmap and prioritize features.
#10 1.518 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
#10 1.519 https://nextjs.org/telemetry
#10 1.520 
#10 1.719 info  - Linting and checking validity of types...
#10 2.747 
#10 2.747 Failed to compile.
#10 2.747 
#10 2.747 ./pages/_app.tsx
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./pages/_document.tsx
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./pages/index.tsx
#10 2.747 2:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./components/Footer.tsx
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./components/Header.tsx
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./components/Page.tsx
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./lib/apolloClient.ts
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./lib/useForm.tsx
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 ./lib/useUser.tsx
#10 2.747 1:1  Error: Parsing error: The keyword 'import' is reserved
#10 2.747 
#10 2.747 info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
#10 2.798 error Command failed with exit code 1.
#10 2.798 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn build]: exit code: 1
ERROR: Service 'ks-frontend-demo' failed to build : Build failed`

So i edited apps/ks-frontend-demo/next.config.js to disable linting during builds, and the error went away.

2) missing lodash types
          Type error: Could not find a declaration file for module 'lodash/isEqual'. '/usr/app/node_modules/lodash/isEqual.js' implicitly has an 'any' type.
      #10 19.99   Try `npm i --save-dev @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash/isEqual';`
      #10 19.99 
      #10 19.99   3 | import { concatPagination } from '@apollo/client/utilities';
      #10 19.99   4 | import merge from 'deepmerge';
      #10 19.99 > 5 | import isEqual from 'lodash/isEqual';
      #10 19.99     |                     ^
      #10 19.99   6 | import getConfig from 'next/config';
      #10 19.99   7 | 
      #10 19.99   8 | export const APOLLO_STATE_PROP_NAME = '__APOLLO_STATE__';
      #10 20.08 
      #10 20.08 > Build error occurred

So I added a `RUN yarn add -D @types/lodash` before yarn install in the docker file, and it worked.
But now..

3)
        ./pages/index.tsx:42:14
        Type error: Property 'itemId' does not exist on type 'Session'.
        
          40 |       )}
          41 |       {!user && <p>No User</p>}
        > 42 |       {data?.itemId ? (
             |              ^
          43 |         <>
          44 |           <p>Your email stored in your NextAuthjs Session as: &quot;{data?.user?.email}&quot;</p>
          45 |           <Button
        
        > Build error occurred

Am I doing something wrong? 
Thanks in advance

**Comment by borisno2** [comment]
Hi @smarques thanks for bringing this up, I was able to replicate and #256 fixes the issue.
