### ISSUE TITLE
authorization in backend example

### ISSUE THREAD

**Issue by smarques** [OpenSaasAU/keystone-nextjs-auth#258]
Hi, I am using your backend example, and there is something that is not clear to me... I expected it to load into session all permission assigned to the user's role..  but when I look at the session object I see only id, name, email.

I believe this is because of this line https://github.com/OpenSaasAU/keystone-nextjs-auth/blob/main/backend/keystone.ts#L25

If I change in keystone.ts :

```
import { permissionsList } from './schemas/permissionFields';
...
sessionData: `id name email role {${permissionsList.join(' ')}}`
```

then everything works!

**Comment by smarques** [comment]
One more thing, I think something is missing here
https://github.com/OpenSaasAU/keystone-nextjs-auth/blob/main/backend/access.ts#L81
```

canManageUsers({ session }: ListAccessArgs) {
    if (!isSignedIn({ session })) {
      return false;
    }
    // Otherwise they may only update themselves!
    return { id: { equals: session?.itemId } };
  },
```
this results in every logged user seeing only their own user record, regardless if they have user management permission or not.
IMHO it should be changed to:

```
canManageUsers({ session }: ListAccessArgs) {
    console.log(session);
    if (!isSignedIn({ session })) {
      return false;
    }
    if (permissions.canManageUsers({ session })) {
      return true;
    }
    // Otherwise they may only update themselves!
    return { id: { equals: session?.itemId } };
  },

```

I can do a PR if you like with these 2 fixes

**Comment by borisno2** [comment]
Yeah, these permissions where setup just as an example, but if you would like to put in a PR that would be great, thanks @smarques
