### ISSUE TITLE
identityField on the provider side

### ISSUE THREAD

**Issue by Francoois** [OpenSaasAU/keystone-nextjs-auth#281]
Hello,
I am trying to make Google Auth work with my Keystone Project.

I got to the point where user is created on sign in, but every time I sign in an attempt is made to create the user again. It leads to an error and I don't have a session.

After some digging in the code, I found out the following is happening :
1. In the `signIn()` callback in NextAuthPage, we check if the user already exist using `validateNextAuth`. We give it the `identityField`, but the `identity` we use to fetch the user is the value of `user.id`.  So in the end `findMatchingIdentity()` makes a bad query, asking for a user whose email adress is its provider ID so it fails.
2. After this we attempt to create a new user from user inputs, with the `identityField` provided by the user. This time data is well formatted so it's a duplicate : rejected.

```ts
async signIn({ user, account, profile }) {
        let identity;
        if (typeof user.id === 'string') {
          identity = user.id;
        } else if (typeof user.id === 'number') {
          identity = user.id;
        } else {
          identity = 0;
        }
        const userInput = resolver ? await resolver({ user, account, profile }) : {};

        const result = await validateNextAuth(identityField, identity, protectIdentities, list);
        // ID
        const data: any = {
          [identityField]: identity,
          ...userInput,
        };

        if (!result.success) {
          if (!autoCreate) {
            return false;
          }

          const createUser = await list
            .createOne({ data })
            .then(returned => {
              return { success: true, user: returned };
            })
            .catch(error => {
              console.error(error);
              throw new Error(error);
            });
          return createUser.success;
        }

        const updateUser = await list
          .updateOne({ where: { id: result.item.id }, data })
          .then(returned => {
            return { success: true, user: returned };
          })
          .catch(error => {
            console.error(error);
            throw new Error(error);
          });
        return updateUser.success;
      }
```

So I'm not sure of the actions to take on my side : 
* Do I have to add the `id` field from the provider user to my database ?
* Should we add a new `providerIdentityField` to match with our DB `identityField`?
* Is the id property of `user` a standard property from OAuth protocol, identical for every provider ?

In my use case using the `email` field from my user List as the identity field feels appropriate so I'd like to stick with it instead of storing google IDs.

**Comment by borisno2** [comment]
Hi @Francoois,
Yes, currently the package is set up to use the OAuth standard `id` - also referred to as the SubjectId. 
This is the standard for a few reasons:
* email addresses can change while the SubjectId will always remain the same
* some auth methods don't use email
* more importantly email addresses - depending on the OAuth provider - can be user-defined, which means a bad actor could signup with your email address using a different provider and gain access to your account, while SubjectId's are unique to a particular "user".

So the way this package works at the moment is to add a `subjectId` or `authId` column to Keystone and set that as your `identityField`

**Comment by Francoois** [comment]
Hi @borisno2, thank you for your reply !
That's what I suspected based on one of your answers about `subjectId`.
I guess in my case (1 Provider : Google Workspace / Company defined

**Comment by borisno2** [comment]
That would be great, thanks @Francoois

**Comment by buzzb0x** [comment]
Hi there, I understand the bad actor concern, but is there a way to match multiple accounts together? What if someone doesn't remember their provider and logs in using another? My use case is to let people authenticate with both Google and email/password, for example.
