### ISSUE TITLE
Compatibility with Keystone's Auth

### ISSUE THREAD

**Issue by adanielyan** [OpenSaasAU/keystone-nextjs-auth#40]
Thank you for working on this great addition to Keystone!

I want to enable both Keystone's built-in auth (https://keystonejs.com/docs/apis/auth) and a social auth for my project. Will this package do both, or do I have to implement the built-in auth separately?

**Comment by borisno2** [comment]
Hi @adanielyan Thanks for reaching out. No, this package doesn't implement the keystone-auth, you could try to implement them side-by-side and hope they nicely together. If you do go down this path I would be interested to hear how it goes and if there is anything that blocks it from this side, I am happy to help.

**Comment by adanielyan** [comment]
Thanks for a quick response! I am currently evaluating a few authentication options and haven't decided on my solution yet. I'll report here if I end-up using your package.

**Comment by k9ordon** [comment]
@adanielyan did it work out for you to use both together?

**Comment by adanielyan** [comment]
After evaluating a few different headless CMSs I decided to go with directus.

**Comment by keystonerjs** [comment]
anyone figured out how integrate keystone auth with next-auth?
